name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    strategy:
      matrix:
        env:
          - sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

          - sdk: macosx
            destination: arch=x86_64

          - sdk: appletvsimulator
            destination: platform=tvOS Simulator,name=Apple TV,OS=latest

    steps:
    - uses: actions/checkout@v1

    - name: Generate Xcode Project
      run: swift package generate-xcodeproj --enable-code-coverage

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        PROJECT: URLNavigator.xcodeproj
        SCHEME: URLNavigator-Package
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}

    - name: Upload Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -J URLNavigator \
          -t caf13cea-d207-454f-be53-78db3160d842
